### ISSUE TITLE
Import trial of `MyProxyClient` in `pyesgf/logon.py` outputs misleading error and incompatibility with `cryptography` from Anaconda `main` channel

### ISSUE THREAD

**Issue by valeriupredoi** [ESGF/esgf-pyclient#83]
@agstephens et al, here are two issues in one, the reason why I chose to open one single issue instead of two is that these two things are related, in actuality it's a cause and effect one:

- main issue: `cryptography` dep from Anaconda/`main` channel is incompatible with `noarch`/`esgf-pyclient=0.3.1` from conda-forge, and am afraid that that exact one gets pulled in when installing esgf-pyclient from conda-forge; the incompatibility throws an openssl-related error from within `cryptography`:
```python
from myproxy.client import MyProxyClient
```
results in
```
Traceback (most recent call last):
  File "/home/valeriu/ESMValCore/testimp.py", line 1, in <module>
    from myproxy.client import MyProxyClient
  File "/home/valeriu/miniconda3/envs/experimental-all-conda/lib/python3.10/site-packages/myproxy/client/__init__.py", line 42, in <module>
    from OpenSSL import crypto, SSL
  File "/home/valeriu/miniconda3/envs/experimental-all-conda/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/valeriu/miniconda3/envs/experimental-all-conda/lib/python3.10/site-packages/OpenSSL/crypto.py", line 11, in <module>
    from OpenSSL._util import (
  File "/home/valeriu/miniconda3/envs/experimental-all-conda/lib/python3.10/site-packages/OpenSSL/_util.py", line 5, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/valeriu/miniconda3/envs/experimental-all-conda/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
(experimental-all-conda) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ vim testimp.py
(experimental-all-conda) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ python testimp.py
Traceback (most recent call last):
  File "/home/valeriu/ESMValCore/testimp.py", line 1, in <module>
    from myproxy.client import MyProxyClient
  File "/home/valeriu/miniconda3/envs/experimental-all-conda/lib/python3.10/site-packages/myproxy/client/__init__.py", line 42, in <module>
    from OpenSSL import crypto, SSL
  File "/home/valeriu/miniconda3/envs/experimental-all-conda/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/valeriu/miniconda3/envs/experimental-all-conda/lib/python3.10/site-packages/OpenSSL/crypto.py", line 11, in <module>
    from OpenSSL._util import (
  File "/home/valeriu/miniconda3/envs/experimental-all-conda/lib/python3.10/site-packages/OpenSSL/_util.py", line 5, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/valeriu/miniconda3/envs/experimental-all-conda/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
```

-> now this is not yer fault since `myproxyclient` is the package that is at fault here, but this is a heads up and maybe you see about this with `myproxyclient` guys

- the secondary issue, which I suggest you guys fix in yer code `pyesgf/logon.py` is related to the main issue but masks it at import trial:
```python
try:
    from myproxy.client import MyProxyClient
    import OpenSSL
    _has_myproxy = True
except (ImportError, SyntaxError):
    _has_myproxy = False
```

please catch the import exception and print it when `_has_myproxy = False` since that way you let the user know what the actual offending import is! :beer:

**Comment by valeriupredoi** [comment]
`myproxyclient` is now me, so am gonna have a quick look now

**Comment by valeriupredoi** [comment]
all deps from conda-forge now, so this can be closed. The try/except import without raising the original exception is not ideal but heyho, the gist is there
